os: linux

language: java
jdk: openjdk11

notifications:
  slack:
    secure: "exsznH/h0Bck7vLKL7lvRNaf1DP+QVZ1XjvtmTUifLw6U5GUspoEnKzYyX9ZpZM0tH+akECwUXA5NYvk2rSmbIOO7/b7sMGq5OSEG5XUCotQzI3/py5uhtU1OrBuYDcXo+Z6KLhqiGQ/6K4f9/s2rcyhTuO8OET+WLRoJ2XEDpFTuDO2EUn+s31+/did631zh6crfHykgGAdVmUfBEeD9nCRn0Z79f8cok3kNaoxYeMcT1GLJ6giDCGBGrm5XtwZmNTy5QQc0DPC/AbaQoVXOBxRHoZQ2Ea1C7WHGJsPj2bssRmiQsVYkSUHra2j73oQoVT2ppo6lyhCCSBaphD2Hf9/lC1vudf/qoOQhbkzQdPteImMEJfle9yFj4KXRn/0igY/a4T2XjWB0JooaP1uZDi70I86izXr7TJJdF9pp+6iy//29sJBF4++F0liT0GyJnsDs+0cyrYw+jhghQwHXCjl9b7ksE/K+UziNvpthhXsWo3YDeayvMLu8GmSetLNewYrvJFHyTnS05hXbbXG3ETAgCT1cxJ1s5wW9vmXm45fGUN1CsbYen8+zekN89Wr2mMQ/br7C7HiBUDdfNSXhje8MamS60S7cuCW7eHBtTxDcjbdbz65BdoSeuFOqC/ZeXHl0qJLyUE8j3r76pHdVK6XcQIhw5e2i0K+y5rl/5Y="

branches:
  only:
    - master
    - develop

# this skips the default ./graldlew assemble task (the actual build script is run in the deploy stage)
install:
  - true

# this skips the default ./graldlew check task
script:
  - true

addons:
  ssh_known_hosts:
    - ituk.ee
  apt:
    packages:
      - sshpass

deploy:
  - provider: script
    script: bash scripts/deploy-master.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy-staging.sh
    on:
      branch: develop