os: linux
language: java
jdk: openjdk11
notifications:
  slack: ituk-dev:sRNXjpzecEiwpjNFsnHTf2bj
branches:
  only:
  - master
  - develop
install:
- true
addons:
  ssh_known_hosts:
  - ituk.ee
  apt:
    packages:
    - sshpass
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
deploy:
- provider: script
  script: bash scripts/deploy-master.sh
  skip_cleanup: true
  on:
    branch: master
