os: linux

language: java
jdk: openjdk11

notifications:
  slack:
    rooms:
      secure: iSaJrTFgMDzicm0rfQpSc5owuE0mI2zRcZ1uoRK8e18io3qFEpZVBwseLLAATlydYYUtWfSGeCjr/0ENh1kQQfaRiEC+pDuABDp7omMIpajmm5NTV6Js6Xaq4xh7Rd6D0FcILstlOPmlSU8FQRb6ipxdFqL1i+u/VJEgxeRqDTH5tBSU5VCRI0AFdpNFsbUyBXn02xDSw1SFVnIiY/wmwk56X7BPEp0u/Yo1azL9+NE5FvYcC6QkIDNWUYTN30nn3GiS9GD5GsMciZpnw2/nSvPcaIA/DBU7JSmuzFQTP7Wyls1fiGXZ1mffXuar68nqPHC7gwQoa79Aa4QrsIrhGxQlWS62V3UWQeEArTqH6h00jQeVeREJO5xN/4xtnaiDWBemyR8yRF00IZYcY9NCNacj2cC4IyQDh8fM4uF3drPKb6dJE2xkbUXFOdF/deW818j3LjLhF9rN3Ysn65cKtluK2+0qjaDr5Ooga1uuBB+AYf5aN77fSUmPG3QfFUqbNt+KFmKuM250yr7VG1gr7ubA8ykjD5PsFXlaEh96+MHvdrmUe9OCMQle5LWPdd9WoGUe9fInNMbqeuE7psC4Opxnqv1NY1TqLB7hAJ7JNT7yGXDnNbQR8NLPjoQKWRm2d5AKQVfjEKLMDp1FC6wcaDq/Vl7KoccB0A8yc/5O64g=

branches:
  only:
    - master
    - develop

# this skips the default ./graldlew assemble task (the actual build script is run in the deploy stage)
install:
  - true

# this skips the default ./graldlew check task
script:
  - true

addons:
  ssh_known_hosts:
    - ituk.ee
  apt:
    packages:
      - sshpass

deploy:
  - provider: script
    script: bash scripts/deploy-master.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy-staging.sh
    on:
      branch: develop