server:
  port: 8081

spring:
  application:
    name: ituk-api
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  datasource:
    url: ${DS_URL}
    username: ${DS_USER}
    password: ${DS_PASSWORD}
    initialization-mode: never
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${DS_URL}
    user: ${DS_USER}
    password: ${DS_PASSWORD}
management:
  endpoint:
    health:
      show-details: always
email:
  domain: ${EMAIL_DOMAIN}
  fromName: ${EMAIL_FROMNAME}
  fromEmail: ${EMAIL_FROMEMAIL}
  apiKey: ${EMAIL_APIKEY}
security:
  signing:
    key: "ituk"
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
logging:
  level:
    DEBUG
file-storage:
  base-dir: "{CHANGE_THIS}"
  mentor-profile-dir: "mentors"

logbook:
  exclude: [ /actuator/health, /v2/**, /swagger-*/**, /webjars/** ]
  write:
    level: TRACE
