server:
  port: 8081

spring:
  application:
    name: ituk-api
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  datasource:
    url: jdbc:postgresql://localhost:5433/ituk-api
    username: postgres
    password: postgres
    initialization-mode: never
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5433/ituk-api
    user: postgres
    password: postgres
management:
  endpoint:
    health:
      show-details: always
email:
  domain: "ituk.ee"
  fromName: "IT teaduskonna üliõpilaskogu"
  fromEmail: "kontakt@ituk.ee"
  apiKey: "I AM KEY"
security:
  signing:
    key: "ituk"
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
logging:
  level:
    DEBUG
file-storage:
  base-dir: "{CHANGE_THIS}"
  mentor-profile-dir: "mentors"

logbook:
  exclude: [ /actuator/health, /v2/**, /swagger-*/**, /webjars/** ]
  write:
    level: TRACE
