spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ituk-api
    username: postgres
    password: postgres
    initialization-mode: never
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: *