spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ituk-api
    username: postgres
    password: postgres
    initialization-mode: never
email:
  domain: "ituk.ee"
  fromName: "IT teaduskonna üliõpilaskogu"
  fromEmail: "kontakt@ituk.ee"
  apiKey: "I AM KEY"

