spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/ituk-api
    username: postgres
    password: postgres
    initialization-mode: never
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
management:
  endpoint:
    health:
      show-details: always
email:
  domain: "ituk.ee"
  fromName: "IT teaduskonna üliõpilaskogu"
  fromEmail: "kontakt@ituk.ee"
  apiKey: "I AM KEY"
security:
  signing:
    key: "ituk"
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
logging:
  level:
    DEBUG
file-storage:
  base-dir: "{CHANGE_THIS}"
  mentor-profile-dir: "mentors"
