server:
  port: 8081

spring:
  application:
    name: ituk-api
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  datasource:
    url: ${DS_URL}
    username: ${DS_USER}
    password: ${DS_PASSWORD}
    initialization-mode: never
  flyway:
    enabled: true
    baseline-on-migrate: true
  cache:
    cache-names:
      - ${rate-limiter.cache-name}
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=60s

management:
  endpoint:
    health:
      show-details: always

email:
  domain: ${EMAIL_DOMAIN}
  fromName: ${EMAIL_FROMNAME}
  fromEmail: ${EMAIL_FROMEMAIL}
  apiKey: ${EMAIL_APIKEY}

security:
  signing:
    key: "ituk"
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
logging:
  level:
    DEBUG
file-storage:
  base-dir: "{CHANGE_THIS}"
  mentor-profile-dir: "mentors"

logbook:
  exclude: [ /actuator/health, /v2/**, /swagger-*/**, /webjars/** ]
  write:
    level: TRACE

bucket4j:
  enabled: true
  filters:
    - cache-name: ${rate-limiter.cache-name}
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes

rate-limiter:
  cache-name: rate-limit-bucket
